### ISSUE TITLE
How to host/deploy this?

### ISSUE THREAD

**Issue by CodyKoInABox** [CodyKoInABox/chatSocketBackend#1]
How/where can I deploy this socket.io server? I've tried vercel, netifly and render but none of them worked.

**Comment by Robert-Wachira** [comment]
Have you tried merging the backend server to be part of the Next.js client side?

**Comment by CodyKoInABox** [comment]
I'm not using any frameworks, the client is hosted on github pages

**Comment by CodyKoInABox** [comment]
I managed to make it work with Render, I was deploying with a couple wrong commands

**Comment by Robert-Wachira** [comment]
Great to hear that.
